//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedBillingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerDetail
    {
        public int BuyerID { get; set; }
        public int BuyerSeq { get; set; }
        public int SaleID { get; set; }
        public int SaleAmount { get; set; }
        public int AmountReceived { get; set; }
        public Nullable<int> Credit { get; set; }
    }
}
