//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedBillingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleMain
    {
        public int SaleID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int BuyerID { get; set; }
        public int TotalSaleAmount { get; set; }
        public int TotalAmountReceived { get; set; }
        public int TotalSaleCredit { get; set; }
    }
}
