//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedBillingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public int StockID { get; set; }
        public int StockSeq { get; set; }
        public int PurchaseID { get; set; }
        public Nullable<decimal> PurchaseQuantity { get; set; }
    }
}
